language: python

before_install:
- gem install travis-artifacts

install: "echo install"
script: "echo script here; echo blargh > output.txt"

after_script: 
- travis-artifacts upload --path output.txt --target-path artifacts/$TRAVIS_REPO_SLUG/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID

env: 
  global: 
  - ARTIFACTS_AWS_REGION=us-west-2
  - ARTIFACTS_S3_BUCKET=artifacts.numenta.org
  - secure: |-
      CJdye71QR+eexESMCd9FsEYB+7IGXkAoIZrJPALAMYhLoPixx5zm4FAFaazX
      vkBQORndufd5b3FTPswQ8Mzwo1epK0gh2H8f/uQzjSJOHa6FufYkpEuoz4wE
      W9eMAH+vxxsPIta2vA6Vyf4faouHZ+A1Bwou3y/EbEl7Rl5sK8g=
  - secure: |-
      lwl7bFPU6dIGWLJfDbnna3OQveRJOhbHKpL58XB3ld2qHQqpTWyYHyMaYHIe
      7ZP7GMJ/lPZyQOq9yWw6/lGEYT6TWEzgTxXH3wV6K+6zTkiCxno0aXMXk4f2
      Z8XjidLTydaxypFf3S05StGkmsb6e7dkvxOcu18khTP1dvV3Gd8=
